#---------------------------------#
#    environment configuration    #
#---------------------------------#

# scripts that run after cloning repository
install:
  - appveyor.install.bat

# enable service required for build/tests
services:
  - mssql2008r2sp2    # start SQL Server 2008 R2 SP2 Express
  - mysql57           # start MySQL 5.7
  - postgresql96      # start PostgreSQL 9.6

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU
platform: Any CPU

# build configuration, i.e. Debug, Release, etc.
configuration: Release

# MSBuild options
build:
  parallel: true
  project: NHibernate.Spatial.sln
  verbosity: minimal

#---------------------------------#
#       tests configuration       #
#---------------------------------#
  
# scripts to run before tests
before_test:
  - appveyor.beforetest.bat
